### ISSUE TITLE
Displacement is broken for BDPT and lightpath

### ISSUE THREAD

**Issue by Vutshi** [mmp/pbrt-v4#385]
Displacement works differently for lightpath, BDPT, and path integrators. Tests are done with pbrt-v4 ffdc4982b34756363a2af2793e8d4fbf43698fee

Lightpath:
![cornell_lightpath_v4](https://github.com/mmp/pbrt-v4/assets/4971779/125774a6-3bb3-4b00-a4eb-4b8ee43fd36c)

BDPT:
![cornell_bdpt_v4](https://github.com/mmp/pbrt-v4/assets/4971779/0a5bb053-dd34-4437-9ace-f5f614822760)

Path:
![cornell_path_v4](https://github.com/mmp/pbrt-v4/assets/4971779/a86e74f9-28a5-4353-80e0-8c335df3fe24)

Ground truth (pbrt-v3 BDPT):
![cornell_bdpt_v3](https://github.com/mmp/pbrt-v4/assets/4971779/3c14dc56-bb6c-4a1a-a6ff-791ebc47ee02)

Scene is using `water-raindrop.png` (and Al_eta for v3) from `barcelona-pavilion`
[cornell_box.pbrt.txt](https://github.com/mmp/pbrt-v4/files/12731135/cornell_box.pbrt.txt)
[cornell_box_v3.pbrt.txt](https://github.com/mmp/pbrt-v4/files/12731139/cornell_box_v3.pbrt.txt)

**Comment by mmp** [comment]
Slightly confusingly, this is actually bump mapping, not displacement mapping. (Which is currently only supported for `plymesh` shapes--this should be fixed...)

I am almost certain that the issue is due to pbrt-v4 not using the appropriate correction factor for shading normals with adjoint light transport. (See Eric Veach's [Non-symmetric Scattering in Light Transport Algorithms](http://luthuli.cs.uiuc.edu/~daf/courses/Rendering/Papers/veachscatter.pdf) paper for details.)  In pbrt-v3, the correction is performed here: https://github.com/mmp/pbrt-v3/blob/13d871faae88233b327d04cda24022b8bb0093ee/src/integrators/bdpt.cpp#L206.

But it is not included in pbrt-v4--here is the corresponding part of the code: https://github.com/mmp/pbrt-v4/blob/6d9d64eac7ac8ba381aa0226531c9ec368991fb4/src/pbrt/cpu/integrators.cpp#L2109.

So why not? The problem is that applying that correction can lead to high variance in many cases. So if the shading normals aren't too far off the geometric normal, not applying the correction may be preferable. You might try re-adding that functionality in pbrt-v4 (and finding the right spot in the `LightPathIntegrator` and applying it there, and see if that makes things match up better.

**Comment by Vutshi** [comment]
> Slightly confusingly, this is actually bump mapping, not displacement mapping.

I agree, the reason I called it displacement is that pbrt-v4 scene format uses “texture displacement” for the bump map. 

Thank you for the suggestion, I will try it. 

Best

**Comment by Vutshi** [comment]
@mmp 

I tested the correction for non-symmetric scattering. It does change things slightly, but it does not address the main issue.

BDPT with correction factor
![cornell_bdpt_new](https://github.com/mmp/pbrt-v4/assets/4971779/7af7b9e6-bd94-435b-adb9-3ab8572613db)


Difference between the new BDPT and old BDPT in part-v4:
![bdpt_diff_nonsym_corrrection](https://github.com/mmp/pbrt-v4/assets/4971779/112a589b-d84e-4c68-bc39-df1f81920c7b)

**Comment by Vutshi** [comment]
> I am almost certain that the issue is due to pbrt-v4 not using the appropriate correction factor for shading normals with adjoint light transport. 

You were right, @mmp — the issue indeed comes from pbrt-v4 not applying the correct shading-normal correction for adjoint light transport.

For some reason `BDPT` was not fully fixed with the above patch, specifically, light reflected directly to the camera from surfaces with shading normals (left wall) wasn’t receiving the correction.

I’ve now applied the correction for `lightpath`. In this case, the correction `CorrectShadingNormal(isect, isect.wo, cs->wi, TransportMode::Importance)` needs to be applied in two places:
in line
https://github.com/mmp/pbrt-v4/blob/91bc6ca69bcdc597d1c8678df088034bf7fbc78c/src/pbrt/cpu/integrators.cpp#L583
This fixes the left wall.

and in line
https://github.com/mmp/pbrt-v4/blob/91bc6ca69bcdc597d1c8678df088034bf7fbc78c/src/pbrt/cpu/integrators.cpp#L594
This resolves the extra corner shadows. Interestingly, the above `BDPT` patch only handled this second part.

New `lightpath`:

<img width="512" height="384" alt="Image" src="https://github.com/user-attachments/assets/7bb96ca9-f19a-4dce-ad98-843ba1fe6755" />

This also appears to fix the new issue https://github.com/mmp/pbrt-v4/issues/526#issue-3676547405  (for `lightpath`).

**Comment by Vutshi** [comment]
Here is how to fix BDPT. There are two locations where the shading-normal correction must be applied:

https://github.com/mmp/pbrt-v4/blob/91bc6ca69bcdc597d1c8678df088034bf7fbc78c/src/pbrt/cpu/integrators.cpp#L1636

https://github.com/mmp/pbrt-v4/blob/91bc6ca69bcdc597d1c8678df088034bf7fbc78c/src/pbrt/cpu/integrators.cpp#L2109

It also fixes https://github.com/mmp/pbrt-v4/issues/526#issue-3676547405 and https://github.com/mmp/pbrt-v4/issues/13#issuecomment-809632771
